/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as TeacherStudentsRouteImport } from './routes/teacher-students'
import { Route as TeacherStudentPreviewRouteImport } from './routes/teacher-student-preview'
import { Route as TeacherReportsRouteImport } from './routes/teacher-reports'
import { Route as TeacherInsightsRouteImport } from './routes/teacher-insights'
import { Route as TeacherDashboardRouteImport } from './routes/teacher-dashboard'
import { Route as TeacherClassesRouteImport } from './routes/teacher-classes'
import { Route as SkillPassportRouteImport } from './routes/skill-passport'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LessonBuilderRouteImport } from './routes/lesson-builder'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GatewaysRouteImport } from './routes/gateways'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as ArchitectureLogRouteImport } from './routes/architecture-log'
import { Route as IndexRouteImport } from './routes/index'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/teacher-students',
  path: '/teacher-students',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentPreviewRoute = TeacherStudentPreviewRouteImport.update({
  id: '/teacher-student-preview',
  path: '/teacher-student-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/teacher-reports',
  path: '/teacher-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherInsightsRoute = TeacherInsightsRouteImport.update({
  id: '/teacher-insights',
  path: '/teacher-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher-dashboard',
  path: '/teacher-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/teacher-classes',
  path: '/teacher-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillPassportRoute = SkillPassportRouteImport.update({
  id: '/skill-passport',
  path: '/skill-passport',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonBuilderRoute = LessonBuilderRouteImport.update({
  id: '/lesson-builder',
  path: '/lesson-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewaysRoute = GatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureLogRoute = ArchitectureLogRouteImport.update({
  id: '/architecture-log',
  path: '/architecture-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture-log': typeof ArchitectureLogRoute
  '/engine': typeof EngineRoute
  '/explore': typeof ExploreRoute
  '/gateways': typeof GatewaysRoute
  '/journal': typeof JournalRoute
  '/lesson-builder': typeof LessonBuilderRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/skill-passport': typeof SkillPassportRoute
  '/teacher-classes': typeof TeacherClassesRoute
  '/teacher-dashboard': typeof TeacherDashboardRoute
  '/teacher-insights': typeof TeacherInsightsRoute
  '/teacher-reports': typeof TeacherReportsRoute
  '/teacher-student-preview': typeof TeacherStudentPreviewRoute
  '/teacher-students': typeof TeacherStudentsRoute
  '/worlds': typeof WorldsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture-log': typeof ArchitectureLogRoute
  '/engine': typeof EngineRoute
  '/explore': typeof ExploreRoute
  '/gateways': typeof GatewaysRoute
  '/journal': typeof JournalRoute
  '/lesson-builder': typeof LessonBuilderRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/skill-passport': typeof SkillPassportRoute
  '/teacher-classes': typeof TeacherClassesRoute
  '/teacher-dashboard': typeof TeacherDashboardRoute
  '/teacher-insights': typeof TeacherInsightsRoute
  '/teacher-reports': typeof TeacherReportsRoute
  '/teacher-student-preview': typeof TeacherStudentPreviewRoute
  '/teacher-students': typeof TeacherStudentsRoute
  '/worlds': typeof WorldsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture-log': typeof ArchitectureLogRoute
  '/engine': typeof EngineRoute
  '/explore': typeof ExploreRoute
  '/gateways': typeof GatewaysRoute
  '/journal': typeof JournalRoute
  '/lesson-builder': typeof LessonBuilderRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/skill-passport': typeof SkillPassportRoute
  '/teacher-classes': typeof TeacherClassesRoute
  '/teacher-dashboard': typeof TeacherDashboardRoute
  '/teacher-insights': typeof TeacherInsightsRoute
  '/teacher-reports': typeof TeacherReportsRoute
  '/teacher-student-preview': typeof TeacherStudentPreviewRoute
  '/teacher-students': typeof TeacherStudentsRoute
  '/worlds': typeof WorldsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture-log'
    | '/engine'
    | '/explore'
    | '/gateways'
    | '/journal'
    | '/lesson-builder'
    | '/login'
    | '/register'
    | '/settings'
    | '/skill-passport'
    | '/teacher-classes'
    | '/teacher-dashboard'
    | '/teacher-insights'
    | '/teacher-reports'
    | '/teacher-student-preview'
    | '/teacher-students'
    | '/worlds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture-log'
    | '/engine'
    | '/explore'
    | '/gateways'
    | '/journal'
    | '/lesson-builder'
    | '/login'
    | '/register'
    | '/settings'
    | '/skill-passport'
    | '/teacher-classes'
    | '/teacher-dashboard'
    | '/teacher-insights'
    | '/teacher-reports'
    | '/teacher-student-preview'
    | '/teacher-students'
    | '/worlds'
  id:
    | '__root__'
    | '/'
    | '/architecture-log'
    | '/engine'
    | '/explore'
    | '/gateways'
    | '/journal'
    | '/lesson-builder'
    | '/login'
    | '/register'
    | '/settings'
    | '/skill-passport'
    | '/teacher-classes'
    | '/teacher-dashboard'
    | '/teacher-insights'
    | '/teacher-reports'
    | '/teacher-student-preview'
    | '/teacher-students'
    | '/worlds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureLogRoute: typeof ArchitectureLogRoute
  EngineRoute: typeof EngineRoute
  ExploreRoute: typeof ExploreRoute
  GatewaysRoute: typeof GatewaysRoute
  JournalRoute: typeof JournalRoute
  LessonBuilderRoute: typeof LessonBuilderRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SkillPassportRoute: typeof SkillPassportRoute
  TeacherClassesRoute: typeof TeacherClassesRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherInsightsRoute: typeof TeacherInsightsRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherStudentPreviewRoute: typeof TeacherStudentPreviewRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  WorldsRoute: typeof WorldsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-students': {
      id: '/teacher-students'
      path: '/teacher-students'
      fullPath: '/teacher-students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-student-preview': {
      id: '/teacher-student-preview'
      path: '/teacher-student-preview'
      fullPath: '/teacher-student-preview'
      preLoaderRoute: typeof TeacherStudentPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-reports': {
      id: '/teacher-reports'
      path: '/teacher-reports'
      fullPath: '/teacher-reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-insights': {
      id: '/teacher-insights'
      path: '/teacher-insights'
      fullPath: '/teacher-insights'
      preLoaderRoute: typeof TeacherInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-dashboard': {
      id: '/teacher-dashboard'
      path: '/teacher-dashboard'
      fullPath: '/teacher-dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-classes': {
      id: '/teacher-classes'
      path: '/teacher-classes'
      fullPath: '/teacher-classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-passport': {
      id: '/skill-passport'
      path: '/skill-passport'
      fullPath: '/skill-passport'
      preLoaderRoute: typeof SkillPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-builder': {
      id: '/lesson-builder'
      path: '/lesson-builder'
      fullPath: '/lesson-builder'
      preLoaderRoute: typeof LessonBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateways': {
      id: '/gateways'
      path: '/gateways'
      fullPath: '/gateways'
      preLoaderRoute: typeof GatewaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture-log': {
      id: '/architecture-log'
      path: '/architecture-log'
      fullPath: '/architecture-log'
      preLoaderRoute: typeof ArchitectureLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureLogRoute: ArchitectureLogRoute,
  EngineRoute: EngineRoute,
  ExploreRoute: ExploreRoute,
  GatewaysRoute: GatewaysRoute,
  JournalRoute: JournalRoute,
  LessonBuilderRoute: LessonBuilderRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SkillPassportRoute: SkillPassportRoute,
  TeacherClassesRoute: TeacherClassesRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherInsightsRoute: TeacherInsightsRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherStudentPreviewRoute: TeacherStudentPreviewRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  WorldsRoute: WorldsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
